### PR TITLE
View updates for levy and commitments

### PR DESCRIPTION
**Pull request by StuartDBaillie**
Updates to the Commitment view to fix formatting
Updates to the Levy view added 2 new columns and fixing issues with Flag_Latest in Test

### CODE REVIEW

**Comment by MichaelYoung1981** [comment]
You've got merge conflicts with a change of Jake's I'm afraid.  Looks like you've both added the same fields to the Levy view.

**Comment by StuartDBaillie** [comment]
I have worked out how to resolve them within the website UI and should have merged now ☺

**Comment by MichaelYoung1981** [comment]
Unfortunately the merge has applied both of your changes which should be mutually exclusive.  Basically, the columns LD.LevyDeclaredInMonth and LD.LevyAvailableInMonth are now in the view twice.

**Comment by StuartDBaillie** [comment]
Okay I will try to fix it again I have noticed he added them at the start and not at the end of the statement

**Comment by benilovj** [comment]
@stuartdbaillie is your stuff ready for another review? I'm keen to get this to Craig ASAP...

**Comment by StuartDBaillie** [comment]
@benilovj  Yeap I believe I have fixed the issue now I have ask Mike to check it before I click the Merge pull request button but if you can that would be great

**Pull request merged**
