### PR TITLE
Add account id

### PR DESCRIPTION
**Pull request by MichaelYoung1981**

### CODE REVIEW

**Comment by benilovj** [comment]
@MichaelYoung1981 out of curiosity, why are we using a hashed account ID, as opposed to the unhashed one?

**Comment by MichaelYoung1981** [comment]
The original understanding was that only the hashed account id should be exposed out of MYA which is why that's all we used in Data.  Unfortunately, it turns out commitments use the internal id which is why we couldn't link accounts and commitments on the reports.

**Comment by benilovj** [comment]
Are we hashing the account ID for security or privacy reasons? I wasn't aware that it's a sensitive identifier...

**Comment by robinoconnor** [comment]
Yes, we are hashing as part of security.

**Pull request merged**
